# Generated by Django 3.0.8 on 2020-09-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listimage',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
